CREATE_ACCOUNT = 0
DEPOSIT = 1
WITHDRAW = 2
CHECK_BALANCE = 3

CREATE_ACCOUNT_SUCCESS = -1
CREATE_ACCOUNT_FAIL = -2
DEPOSIT_SUCCESS = -3
DEPOSIT_FAIL = -4
WITHDRAW_SUCCESS = -5
WITHDRAW_FAIL = -6
BALANCE_SUCCESS = -7
BALANCE_FAIL = -8
